const ACTION_TYPES = {
  //counter
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',
  //todo
  CREATED_TASK:'CREATED_TASK',
  UPDATE_TASK:'UPDATE_TASK',
  DELETE_TASK:'DELETE_TASK',
  //SET_FILTER_TASK

  //USER
  CREATE_USER_REQUEST:'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR:'CREATE_USER_ERROR',
}

export default ACTION_TYPES;