const ACTION_TYPES = {
  //counter
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',
  //todo
  CREATED_TASK:'CREATED_TASK',
  UPDATE_TASK:'UPDATE_TASK',
  DELETE_TASK:'DELETE_TASK',
  //SET_FILTER_TASK
}

export default ACTION_TYPES;